// Generated by tool/generate_tokens.dart from Uptrack web tokens.
// Do not edit. Run dart run tool/generate_tokens.dart --check.
import 'package:flutter/material.dart';

abstract final class UptrackColors {
  static const Color lightBackground = Color(0xFFFFFFFF);
  static const Color lightSurface = Color(0xFFFFFFFF);
  static const Color lightSurfaceRaised = Color(0xFFF1F4F8);
  static const Color lightBand = Color(0xFFF5F7FA);
  static const Color lightForeground = Color(0xFF0E1520);
  static const Color lightBody = Color(0xFF3D4A5C);
  static const Color lightMutedForeground = Color(0xFF5E6B7D);
  static const Color lightBorder = Color(0xFFE3E8EF);
  static const Color lightInput = Color(0xFFD5DCE6);
  static const Color lightPrimary = Color(0xFF1F5AD6);
  static const Color lightOnPrimary = Color(0xFFFFFFFF);
  static const Color lightCta = Color(0xFF0E1520);
  static const Color lightOnCta = Color(0xFFFFFFFF);
  static const Color lightDestructive = Color(0xFFBC4123);
  static const Color darkBackground = Color(0xFF0A0E14);
  static const Color darkSurface = Color(0xFF111822);
  static const Color darkSurfaceRaised = Color(0xFF18212D);
  static const Color darkBand = Color(0xFF111822);
  static const Color darkForeground = Color(0xFFEEF2F6);
  static const Color darkBody = Color(0xFFBAC5D2);
  static const Color darkMutedForeground = Color(0xFF8795A8);
  static const Color darkBorder = Color(0xFF243041);
  static const Color darkInput = Color(0xFF2B3848);
  static const Color darkPrimary = Color(0xFF8FB2F2);
  static const Color darkOnPrimary = Color(0xFF0A0E14);
  static const Color darkCta = Color(0xFFF2F5F8);
  static const Color darkOnCta = Color(0xFF0A0E14);
  static const Color darkDestructive = Color(0xFFEE7A63);
  static const Color upLight = Color(0xFF387048);
  static const Color upSoftLight = Color(0xFFE6F0E8);
  static const Color upDark = Color(0xFF7FB08A);
  static const Color upSoftDark = Color(0xFF2B3A30);
  static const Color downLight = Color(0xFFB03B1F);
  static const Color downSoftLight = Color(0xFFF6E3DD);
  static const Color downDark = Color(0xFFEE7A63);
  static const Color downSoftDark = Color(0xFF3B2B27);
  static const Color degradedLight = Color(0xFF8A6400);
  static const Color degradedSoftLight = Color(0xFFF4ECD6);
  static const Color degradedDark = Color(0xFFE0B354);
  static const Color degradedSoftDark = Color(0xFF3A3320);
  static const Color pausedLight = Color(0xFF476685);
  static const Color pausedSoftLight = Color(0xFFE3EAF1);
  static const Color pausedDark = Color(0xFF8AA8C4);
  static const Color pausedSoftDark = Color(0xFF28323C);
  static const Color unknownLight = Color(0xFF526176);
  static const Color unknownSoftLight = Color(0xFFE6EBF1);
  static const Color unknownDark = Color(0xFF93A2B6);
  static const Color unknownSoftDark = Color(0xFF232D3A);
}
