#!/usr/bin/env python3
"""Generate every Uptrack app and web icon from the SVG masters in design/icon/.

Usage (from the uptrack-mobile root):
    python3 tool/gen_icons.py [path/to/uptrack-web/public]

Needs rsvg-convert (librsvg) and Pillow. The web folder is optional; without it
only the mobile icons are written.
"""

from __future__ import annotations

import io
import json
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "design" / "icon"

TILE = "#F5F7FA"
INK = "#0E1520"
GREEN = "#2FBF71"

# The mark, in the 1024 icon space. Keep in sync with design/icon/*.svg.
U_PATH = "M320,332 V562 A162,162 0 0 0 644,562 V530"
U_STROKE = 112
DOT = (644, 330, 74)
HALO = (644, 330, 118, 18, 0.35)


def svg(name: str) -> str:
    return (SRC / name).read_text()


def render(svg_text: str, size: int) -> Image.Image:
    png = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size)],
        input=svg_text.encode(),
        capture_output=True,
        check=True,
    ).stdout
    return Image.open(io.BytesIO(png)).convert("RGBA")


def opaque(im: Image.Image) -> Image.Image:
    """App Store icons must have no alpha channel."""
    bg = Image.new("RGB", im.size, TILE)
    bg.paste(im, mask=im.split()[3])
    return bg


def rounded(svg_text: str) -> str:
    return svg_text.replace(f'<rect width="1024" height="1024" fill="{TILE}"/>',
                            f'<rect width="1024" height="1024" rx="229" fill="{TILE}"/>')


def full_bleed(svg_text: str) -> str:
    return svg_text.replace(' rx="229"', "")


def circle_path(cx: float, cy: float, r: float) -> str:
    return f"M{cx - r},{cy} a{r},{r} 0 1,0 {2 * r},0 a{r},{r} 0 1,0 {-2 * r},0"


def write(path: Path, data: bytes | str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(data, str):
        path.write_text(data)
    else:
        path.write_bytes(data)
    print("wrote", path.relative_to(path.parents[3]) if len(path.parents) > 3 else path)


def save_png(im: Image.Image, path: Path) -> None:
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    write(path, buf.getvalue())


# ---------------------------------------------------------------- iOS

def ios() -> None:
    icon, small = svg("app-icon.svg"), full_bleed(svg("app-icon-small.svg"))
    folder = ROOT / "ios/Runner/Assets.xcassets/AppIcon.appiconset"
    contents = json.loads((folder / "Contents.json").read_text())
    for image in contents["images"]:
        points = float(image["size"].split("x")[0])
        px = round(points * int(image["scale"].rstrip("x")))
        # Below ~88 px the halo ring turns to blur, so use the larger mark.
        save_png(opaque(render(small if px < 88 else icon, px)), folder / image["filename"])
    save_png(opaque(render(icon, 1024)), ROOT / "assets/app-icon-master-1024.png")
    save_png(opaque(render(icon, 1024)), ROOT / "store/icon/app-store-1024.png")


# ---------------------------------------------------------------- Android

def vector(viewport: int, group_attrs: str, paths: list[str], size_dp: int) -> str:
    body = "\n".join(f"        {p}" for p in paths)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_icons.py from design/icon/. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size_dp}dp"
    android:height="{size_dp}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
    <group {group_attrs}>
{body}
    </group>
</vector>
"""


def mark_paths(u: str, dot: str, halo: str | None) -> list[str]:
    paths = [
        f'<path android:pathData="{U_PATH}" android:strokeColor="{u}" '
        f'android:strokeWidth="{U_STROKE}" android:strokeLineCap="round" />',
        f'<path android:pathData="{circle_path(*DOT)}" android:fillColor="{dot}" />',
    ]
    if halo:
        cx, cy, r, w, a = HALO
        paths.append(
            f'<path android:pathData="{circle_path(cx, cy, r)}" android:strokeColor="{halo}" '
            f'android:strokeWidth="{w}" android:strokeAlpha="{a}" />'
        )
    return paths


def android() -> None:
    res = ROOT / "android/app/src/main/res"
    # Adaptive icon: 108 dp canvas, of which the launcher shows the middle 72 dp.
    # The 1024 design space maps to those 72 dp (viewport 1536 = 1024 * 108 / 72),
    # and the mark is scaled 1.12 so it fills the circle mask like the iOS tile.
    adaptive = ('android:pivotX="512" android:pivotY="512" android:scaleX="1.12" '
                'android:scaleY="1.12" android:translateX="256" android:translateY="256"')
    write(res / "drawable/ic_launcher_foreground.xml",
          vector(1536, adaptive, mark_paths(INK, GREEN, GREEN), 108))
    write(res / "drawable/ic_launcher_monochrome.xml",
          vector(1536, adaptive, mark_paths("#FFFFFF", "#FFFFFF", None), 108))
    # Status-bar notification icon: white silhouette, cropped like the web mark.
    write(res / "drawable/ic_notification.xml",
          vector(600, 'android:translateX="-191" android:translateY="-218"',
                 mark_paths("#FFFFFF", "#FFFFFF", None), 24))
    old_png = res / "drawable/ic_launcher_foreground.png"
    if old_png.exists():
        old_png.unlink()
        print("removed", old_png.name)

    colors = res / "values/colors.xml"
    text = colors.read_text()
    text = re.sub(r'(<color name="ic_launcher_background">)[^<]*(</color>)', rf"\g<1>{TILE}\g<2>", text)
    write(colors, text)

    # Legacy icons (Android 7 and older, which ignore adaptive icons).
    small = svg("app-icon-small.svg")
    for density, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        save_png(render(small, px), res / f"mipmap-{density}/ic_launcher.png")

    # Play Console store icon: 512 px, full bleed; Google applies the mask.
    save_png(render(svg("app-icon.svg"), 512), ROOT / "store/icon/play-512.png")


# ---------------------------------------------------------------- wordmark

FONT = ROOT / "assets/fonts/IBMPlexSans-SemiBold.ttf"
LIGHT_UI_INK, DARK_UI_INK = INK, "#EEF2F6"


def wordmark(height: int, ink: str) -> Image.Image:
    """The mark as the capital "U", then "ptrack": the logo reads "Uptrack".

    IBM Plex Sans SemiBold, transparent canvas. The U body is cap height and sits
    on the baseline; its stroke is thinned from 112 to 88 so it sits closer to the
    letter weight. Drawn at 4x and scaled down so edges stay smooth.
    """
    from PIL import ImageDraw, ImageFont

    k = 4
    h = height * k
    font = ImageFont.truetype(str(FONT), int(h * 0.74))
    asc_top = font.getbbox("k")[1]          # top of the tallest letter
    cap_top = font.getbbox("H")[1]          # top of a capital
    baseline = font.getmetrics()[0]
    desc = font.getbbox("p")[3] - baseline  # depth of the "p" tail
    text_h = baseline - asc_top + desc
    pad = (h - text_h) // 2
    y_text = pad - asc_top                  # where PIL draws the text origin
    base_y = y_text + baseline

    # Tight crop of the thinner U + dot: x 276..718, y 256..768. The U body
    # (stroke top 288 to bottom 768) is 480 units; the dot rises 32 above it.
    mark_svg = svg("mark-light.svg").replace('viewBox="191 218 600 600"', 'viewBox="276 256 442 512"')
    mark_svg = (mark_svg.replace('width="600" height="600"', 'width="442" height="512"')
                .replace('stroke-width="112"', 'stroke-width="88"').replace(INK, ink))
    cap_h = base_y - (y_text + cap_top)
    mark_h = round(cap_h * 512 / 480)
    mark_w = round(mark_h * 442 / 512)
    png = subprocess.run(["rsvg-convert", "-w", str(mark_w), "-h", str(mark_h)],
                         input=mark_svg.encode(), capture_output=True, check=True).stdout
    mark = Image.open(io.BytesIO(png)).convert("RGBA")

    gap = int(font.size * 0.05)
    text_w = int(font.getlength("ptrack"))
    canvas = Image.new("RGBA", (k + mark_w + gap + text_w + 2 * k, h), (0, 0, 0, 0))
    canvas.alpha_composite(mark, (k, base_y - mark_h))
    ImageDraw.Draw(canvas).text((k + mark_w + gap, y_text), "ptrack", font=font, fill=ink)
    w = round(canvas.width / k)
    return canvas.resize((w, height), Image.LANCZOS)


def on_background(im: Image.Image, size: tuple[int, int], bg: str, height: int) -> Image.Image:
    """Centre a wordmark of the given height on a solid background."""
    mark = im.resize((round(im.width * height / im.height), height), Image.LANCZOS)
    out = Image.new("RGB", size, bg)
    out.paste(mark, ((size[0] - mark.width) // 2, (size[1] - mark.height) // 2), mark)
    return out


def mobile_brand() -> None:
    for name, ink in {"light": LIGHT_UI_INK, "dark": DARK_UI_INK}.items():
        save_png(wordmark(144, ink), ROOT / f"assets/brand/uptrack-wordmark-{name}.png")


# ---------------------------------------------------------------- web

def web(public: Path) -> None:
    icon, small = svg("app-icon.svg"), svg("app-icon-small.svg")
    write(public / "favicon.svg", small)
    write(public / "uptrack-logo.svg", icon)
    for px in (16, 32):
        save_png(render(small, px), public / f"favicon-{px}.png")
    # Google Search wants a favicon that is a multiple of 48 px.
    save_png(render(rounded(icon), 96), public / "favicon-96.png")
    ico = render(small, 256)
    buf = io.BytesIO()
    ico.save(buf, "ICO", sizes=[(16, 16), (32, 32), (48, 48)])
    write(public / "favicon.ico", buf.getvalue())
    # iOS home-screen bookmark: full bleed and opaque; iOS rounds the corners.
    save_png(opaque(render(icon, 180)), public / "apple-touch-icon.png")
    for name, px in {"icon-192.png": 192, "icon-512.png": 512, "logo192.png": 192, "logo512.png": 512}.items():
        save_png(render(rounded(icon), px), public / name)
    jpg = io.BytesIO()
    opaque(render(icon, 1024)).save(jpg, "JPEG", quality=92)
    write(public / "uptrack-logo.jpg", jpg.getvalue())
    # Small UI mark next to the product name (dashboard sidebar).
    save_png(render(svg("mark-dark.svg"), 192), public / "uptrack-mark.png")
    save_png(render(svg("mark-light.svg"), 192), public / "uptrack-mark-light.png")
    # Wordmark: site header, login, signup, OG images (2x for sharp edges).
    light, dark = wordmark(144, LIGHT_UI_INK), wordmark(144, DARK_UI_INK)
    save_png(light, public / "uptrack-wordmark-light.png")
    save_png(dark, public / "uptrack-wordmark-dark.png")
    print(f"wordmark aspect {light.width}x{light.height}")
    # Fixed-size logo files: Google Organization logo (schema.ts), emails, wide banner.
    save_png(on_background(light, (200, 78), "#FFFFFF", 34), public / "uptrack-logo-header.png")
    save_png(on_background(light, (400, 156), "#FFFFFF", 64), public / "uptrack-logo-email.png")
    save_png(on_background(dark, (1024, 400), "#0A0E14", 150), public / "uptrack-logo-wide.png")


if __name__ == "__main__":
    ios()
    android()
    mobile_brand()
    if len(sys.argv) > 1:
        web(Path(sys.argv[1]).resolve())
