import 'dart:convert';
import 'dart:io';

/// Run from the mobile root. Only writes the mobile output; --check is read-only.
void main(List<String> args) {
  try {
    final sourceIndex = args.indexOf('--source');
    if (sourceIndex >= 0 && sourceIndex + 1 == args.length) {
      throw const FormatException('--source requires a JSON path');
    }
    final source = File(
      sourceIndex < 0
          ? '../uptrack-web/design/tokens.json'
          : args[sourceIndex + 1],
    );
    final tokens =
        (jsonDecode(source.readAsStringSync()) as Map)['tokens'] as Map;
    const roles = <String, String>{
      'Background': 'background',
      'Surface': 'card',
      'SurfaceRaised': 'muted',
      'Band': 'band',
      'Foreground': 'foreground',
      'Body': 'body',
      'MutedForeground': 'muted-foreground',
      'Border': 'border',
      'Input': 'input',
      'Primary': 'primary',
      'OnPrimary': 'primary-foreground',
      'Cta': 'cta',
      'OnCta': 'cta-foreground',
      'Destructive': 'destructive',
    };
    String color(String role, String mode) {
      final hex = (tokens[role] as Map?)?[mode];
      if (hex is! String || !RegExp(r'^#[0-9a-fA-F]{6}$').hasMatch(hex)) {
        throw FormatException('Missing or invalid $role.$mode');
      }
      return 'Color(0xFF${hex.substring(1).toUpperCase()})';
    }

    final out = StringBuffer(
      '// Generated by tool/generate_tokens.dart from Uptrack web tokens.\n'
      '// Do not edit. Run dart run tool/generate_tokens.dart --check.\n'
      "import 'package:flutter/material.dart';\n\nabstract final class UptrackColors {\n",
    );
    for (final mode in ['light', 'dark']) {
      for (final role in roles.entries) {
        out.writeln(
          '  static const Color $mode${role.key} = ${color(role.value, mode)};',
        );
      }
    }
    for (final status in ['up', 'down', 'degraded', 'paused', 'unknown']) {
      for (final mode in ['light', 'dark']) {
        final suffix = '${mode[0].toUpperCase()}${mode.substring(1)}';
        out.writeln(
          '  static const Color $status$suffix = ${color('status-$status', mode)};',
        );
        out.writeln(
          '  static const Color ${status}Soft$suffix = ${color('status-$status-soft', mode)};',
        );
      }
    }
    out.writeln('}');
    final artifacts = <String, String>{
      'lib/theme/colors.g.dart': out.toString(),
    };
    const nativeRoles = {
      'surface': 'card',
      'foreground': 'foreground',
      'muted': 'muted-foreground',
    };
    for (final mode in ['light', 'dark']) {
      final xml = StringBuffer(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated from shared Uptrack tokens. Do not edit. -->\n<resources>\n',
      );
      for (final role in nativeRoles.entries) {
        xml.writeln(
          '  <color name="uptrack_widget_${role.key}">${(tokens[role.value] as Map)[mode]}</color>',
        );
      }
      xml.writeln('</resources>');
      artifacts['android/app/src/main/res/${mode == 'light' ? 'values' : 'values-night'}/uptrack_design_colors.xml'] =
          xml.toString();
    }
    String uiColor(String role, String mode) {
      final hex = (tokens[role] as Map)[mode] as String;
      final values = [
        for (var i = 1; i < 7; i += 2)
          (int.parse(hex.substring(i, i + 2), radix: 16) / 255).toStringAsFixed(
            8,
          ),
      ];
      return 'UIColor(red: ${values[0]}, green: ${values[1]}, blue: ${values[2]}, alpha: 1)';
    }

    final swift = StringBuffer(
      '// Generated from shared Uptrack tokens. Do not edit.\nimport SwiftUI\nimport UIKit\n\nenum UptrackInk {\n',
    );
    // Status colors for the Live Activity and widget (design A). iOS only:
    // the Android widget keeps its own layout, so its resources do not change.
    const iosStatusRoles = {
      'primary': 'primary',
      'up': 'status-up',
      'upSoft': 'status-up-soft',
      'down': 'status-down',
      'downSoft': 'status-down-soft',
    };
    for (final role in [...nativeRoles.entries, ...iosStatusRoles.entries]) {
      swift.writeln(
        '  static let ${role.key} = Color(uiColor: UIColor { traits in\n    traits.userInterfaceStyle == .dark ? ${uiColor(role.value, 'dark')} : ${uiColor(role.value, 'light')}\n  })',
      );
    }
    swift.writeln('}');
    artifacts['ios/Runner/Widget/UptrackInk.g.swift'] = swift.toString();
    // Check every output before any write; invalid inputs cannot partially update artifacts.
    if (args.contains('--check')) {
      for (final artifact in artifacts.entries) {
        final file = File(artifact.key);
        if (!file.existsSync() || file.readAsStringSync() != artifact.value) {
          throw FormatException(
            'Missing or stale ${artifact.key}. Run dart run tool/generate_tokens.dart.',
          );
        }
      }
      stdout.writeln(
        'Mobile shared tokens are current (Flutter, Android, iOS).',
      );
    } else {
      for (final artifact in artifacts.entries) {
        final file = File(artifact.key)..parent.createSync(recursive: true);
        file.writeAsStringSync(artifact.value);
      }
    }
  } catch (error) {
    stderr.writeln('Token generation failed: $error');
    exitCode = 1;
  }
}
